# permissions for end users to edit redisclones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisclone-editor-role
rules:
- apiGroups:
  - operator.bobfintech.com
  resources:
  - redisclones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.bobfintech.com
  resources:
  - redisclones/status
  verbs:
  - get
