# permissions for end users to view redisbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisbackup-viewer-role
rules:
- apiGroups:
  - operator.bobfintech.com
  resources:
  - redisbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.bobfintech.com
  resources:
  - redisbackups/status
  verbs:
  - get
