# permissions for end users to view redisclones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisclone-viewer-role
rules:
- apiGroups:
  - operator.bobfintech.com
  resources:
  - redisclones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.bobfintech.com
  resources:
  - redisclones/status
  verbs:
  - get
