## Append samples you want in your CSV to this file as resources ##
resources:
- operator_v1alpha1_redisbackup.yaml
- operator_v1alpha1_redisclone.yaml
- redis-operate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
