apiVersion: operator.bobfintech.com/v1alpha1
kind: RedisBackup
metadata:
  name: redisbackup
spec:
  # Add fields here
  clusterName: test
  backupSecretName: redis-backup-secret333
  backupURL: s3://velero/
  expireDays: "1"
  backupSchedule: "* * * * *"