apiVersion: v1
kind: Secret
metadata:
  name: redis-backup-secret333
type: Opaque
data:
    S3Region: cmVnaW9uMQ==
    S3Endpoint: aHR0cDovL21pbmlvLnZlbGVyby5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw
    S3AccessKey: bWluaW8=
    S3SecretKey: bWluaW8xMjM=
    S3Bucket: dmVsZXJv