apiVersion: v1
kind: Secret
metadata:
  name: redis-backup-secret
type: Opaque
data:
    # eg base64(region1)
    S3Region: cmVnaW9uMQ==
    # eg base64(http://IP+PORT)
    S3Endpoint: aHR0cDovL21pbmlvLnZlbGVyby5zdmMuY2x1c3Rlci5sb2NhbDo5MDAw
    # eg base64(minio)
    S3AccessKey: bWluaW8=
    # eg base64(minio123)
    S3SecretKey: bWluaW8xMjM=